### ISSUE TITLE
Questions about gpu batched nms

### ISSUE THREAD

**Issue by youngjae-avikus** [marcoslucianops/DeepStream-Yolo#192]
The cluster_mode in the config is set to 4, but did you improve the post-processing by squeezing the code yourself?
In other words, it seems that you did not use clustering provided by deepstream, and you put in the code yourself
Can you tell me exactly which part it is?
Thank you

**Comment by youngjae-avikus** [comment]
@marcoslucianops 

Did you have that experience in tenssort7

**Comment by nemosupremo** [comment]
@marcoslucianops 

It seems GPU Batched NMS has a 66% performance improvement which is amazing, but a drawback here is the TensorRT engine needs to be rebuilt if the iou/score/topk changes + not being able to per-class config options.

Is it possible to support both modes (use CPU when `cluster-mode=2` and GPU when `cluster-mode=4`)?

**Comment by marcoslucianops** [comment]
@youngjae-avikus, in what specifically?

@nemosupremo, you can use the per-class config (`class-attrs-0`, `class-attrs-1`, etc). The `score-threshold` will work as minimum score, then the `pre-cluster-threshold` will filter the scores according to each object (the same goes for the `topk`). The `cluster-mode=2` only uses the `nms-iou-threshold` value. It's possible to change the code to use each one according to the `cluster-mode` but, in my opinion, it's not necessary because the improvement of GPU Batched NMS is too big.

Note: Using `pre-cluster-threshold` and  `topk` in `[class-attrs]` section will increase the CPU usage and may decrease the performance.

**Comment by youngjae-avikus** [comment]
@marcoslucianops 

about [TensorRT BatchedNMS plugin](https://github.com/NVIDIA/TensorRT/tree/main/plugin/batchedNMSPlugin)

**Comment by nemosupremo** [comment]
@marcoslucianops 

So if I have 3 classes, 1`0`, `1`, `3` in my config I will have:

```
[class-attrs-0]
pre-cluster-threshold=0.2
nms-iou-threshold=.213
[class-attrs-1]
pre-cluster-threshold=0.4
nms-iou-threshold=.4
[class-attrs-3]
pre-cluster-threshold=0.5
nms-iou-threshold=.5
```

Then in my `config_nms` I would have to do something like:

```
[property]
iou-threshold=min(nms-iou-threshold)
score-threshold=min(pre-cluster-threshold)
topk=300
```

Correct?

**Comment by marcoslucianops** [comment]
@youngjae-avikus, There's the same function for TensorRT 7 (`createBatchedNMSPlugin()`) but it's easy to use from the plugins too.

@nemosupremo, the `nms-iou-threshold` only works with `cluster-mode=2`, which is disabled ( `cluster-mode=4`) due to GPU BatchedNMS. You should use only the `pre-cluster-threshold` key.

**Comment by marcoslucianops** [comment]
@nemosupremo, yes

**Comment by youngjae-avikus** [comment]
I want to activate the class agnostic nms option, can I control it from the tensorrt nms plug-in to the coded?

@marcoslucianops

**Comment by marcoslucianops** [comment]
@youngjae-avikus, I'm not familiar with agnostic nms, but I think you need to change the yoloLayer outputs to fit the batchedNMSPlugin input with `shareLocation = false` and the output shape. You probably need to change the logic to add all classes to the output bbox instead of the maxProb class.

**Comment by youngjae-avikus** [comment]
@marcoslucianops 

Thank you. I'll try it over time
Please don't close the issue for a while

**Comment by adimukewar** [comment]
Is topk filter for nms applied before or after the NMS GPU implementation?
When I increase the topk, higher confidence bounding boxes appear. Also, total number of objects detected is same in both scenarios.

**Comment by marcoslucianops** [comment]
@adimukewar, the topK is applied to limit the outputs before the NMS (yoloLayer) and during the NMS (GPU Batched NMS).

**Comment by marcoslucianops** [comment]
New optimized NMS https://github.com/marcoslucianops/DeepStream-Yolo/issues/142
