### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by formerlya** [marcoslucianops/DeepStream-Yolo#208]
![image](https://user-images.githubusercontent.com/88373367/179210253-06fd9519-e2ec-48ab-892c-0dedb814c2fb.png)
yolov5 v5.0
tensorrt v5.0
when I use the .wts .engine .cfg made by tensorrt, in tensorrt it test good.
①When I put them into deepstream
![image](https://user-images.githubusercontent.com/88373367/179210550-678bc146-f7a8-438a-b349-63972aea66ff.png)
and use deepstream-app -c deepstream_app_config.txt
![image](https://user-images.githubusercontent.com/88373367/179211260-d83e41a1-f4fd-4462-9d43-2888a99e1b28.png)
②When I put them and load libmyplugins.so 
and use LD_PRELOAD=./libmyplugins.so deepstream-app -c deepstream_app_config.txt
![image](https://user-images.githubusercontent.com/88373367/179211864-2d6688fe-599b-4b27-b806-d51aca273c6d.png)
![image](https://user-images.githubusercontent.com/88373367/179211904-27ee7fc7-1882-47ab-9118-297a44785dfd.png)
Then
![image](https://user-images.githubusercontent.com/88373367/179211995-11cd5e76-5c03-4c80-a937-19b71bdb477d.png)
……
I don't know why……

**Comment by marcoslucianops** [comment]
https://github.com/marcoslucianops/DeepStream-Yolo#requirements

https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/docs/YOLOv5.md

**Comment by formerlya** [comment]
The file generated by tensorrt can't work for deepstream?
But, I see version 5.1 deepstream tutorial can realize, 6.0 series can't?
jetson+yolov5+tenssort+deepstream6.0's imformation is too little to learn, pure beginner.
o(╥﹏╥)o

**Comment by marcoslucianops** [comment]
I should not work in the latest repo files. Please use the `gen_wts_yoloV5.py` file to convert the YOLOv5 models.

**Comment by tunesh** [comment]
Hi, I am having a "segmentation fault" error.  This error comes only a few times. Rest of the time the pipeline works fine. The error comes when the pipeline loads again for processing when we send it a message.

[Ubuntu 20.04]
[CUDA 11.6 ]
   
[NVIDIA Driver 510.47.03]
[NVIDIA DeepStream SDK 6.1]
[GStreamer 1.16.2]
[DeepStream-Yolo]


0:00:52.974549997   140      0x449bd00 INFO                 nvinfer gstnvinfer.cpp:646:gst_nvinfer_logger:<secondary2-nvinference-engine> NvDsInferContext[UID 2]: Info from NvDsInferContextImpl::deserializeEngineAndBackend() <nvdsinfer_context_impl.cpp:1909> [UID = 2]: deserialized trt engine from :/opt/nvidia/deepstream/deepstream-6.1/sources/deepstream_python_apps/apps/instagng_ds_inventory/test2.onnx_b1_gpu0_fp32.engine
WARNING: [TRT]: The getMaxBatchSize() function should not be used with an engine built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. This function will always return 1.
INFO: ../nvdsinfer/nvdsinfer_model_builder.cpp:610 [Implicit Engine Info]: layers num: 3
0   INPUT  kFLOAT input:0         3x224x224       
1   OUTPUT kFLOAT dropout_1       128             
2   OUTPUT kFLOAT dense           29              

0:00:52.975675261   140      0x449bd00 INFO                 nvinfer gstnvinfer.cpp:646:gst_nvinfer_logger:<secondary2-nvinference-engine> NvDsInferContext[UID 2]: Info from NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:2012> [UID = 2]: Use deserialized engine model: /opt/nvidia/deepstream/deepstream-6.1/sources/deepstream_python_apps/apps/instagng_ds_inventory/test2.onnx_b1_gpu0_fp32.engine
0:00:52.976119747   140      0x449bd00 INFO                 nvinfer gstnvinfer_impl.cpp:328:notifyLoadModelStatus:<secondary2-nvinference-engine> [UID 2]: Load new model:test_classifier_config_dli.txt successfully
Segmentation fault (core dumped)


Ideally after "nvinference-engine> [UID 2]: Load new model:test_classifier_config_dli.txt successfully" the following should happen.

Deserialize yoloLayer plugin: yolo
0:00:41.326322620   140      0x449bd00 INFO                 nvinfer gstnvinfer.cpp:646:gst_nvinfer_logger:<primary-inference> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::deserializeEngineAndBackend() <nvdsinfer_context_impl.cpp:1909> [UID = 1]: deserialized trt engine from :/opt/nvidia/deepstream/deepstream-6.1/sources/deepstream_python_apps/apps/instagng_ds_inventory/model_b2_gpu0_fp32.engine
INFO: ../nvdsinfer/nvdsinfer_model_builder.cpp:610 [Implicit Engine Info]: layers num: 5
0   INPUT  kFLOAT data            3x608x608       
1   OUTPUT kFLOAT num_detections  1               
2   OUTPUT kFLOAT detection_boxes 22743x4         
3   OUTPUT kFLOAT detection_scores 22743           
4   OUTPUT kFLOAT detection_classes 22743        

I believe, because of deserializing, it's giving this error. Please help!!

**Comment by marcoslucianops** [comment]
Can you use gdb to debug the segmentation fault?

**Comment by lyj201644070230** [comment]
> 

您好，我也遇到跟你同样的问题？请问您解决了吗？

**Comment by tuneshverma** [comment]
Hi, no I was not able to solve it.

**Comment by marcoslucianops** [comment]
Try using the new ONNX export method.

**Comment by Bo-Yu-Columbia** [comment]
Hi! I am also having this problem, only except that I have segmentation fault 9 times out of 10, Is there any way to fix this? I'm using custom yolov8 model, followed the steps in the project(running  on DeepStream 6.2)
