### ISSUE TITLE
difference python biding and deepstream_app_config.txt

### ISSUE THREAD

**Issue by khosrooo** [marcoslucianops/DeepStream-Yolo#444]
Hi Sir, i have a little confuse , i get kittie-out put in python with  " f.write("[{}]".format(",".join(str(x) for x in [obj_meta.confidence, int(rect_params.left), int(rect_params.top), int(rect_params.width+rect_params.left), int(rect_params.height+rect_params.top)])))" and save in txt files but when compare with txt files created by deepstream_app_config.txt (not python) , i see the python biding can not detect in frame 0,1,2,3,4 and txt file is empthy  and detection is weaker than deepstream_app_config.txt  (for example number of detection is lower) do u have idea about that , it is related the python biding dose not use mp4 and used h264 format ??,
Thank u for supported.

**Comment by marcoslucianops** [comment]
Are you using exactly the same config in both cases? I mean the same config_infer file, same streammux options, with/without tracker in both, etc? Probably, you aren't getting the first 5 frames due to the tracker age (it takes few frames to set the object as true object in the meta and the number of frames it takes depends on its configuration in the yaml file).

**Comment by khosrooo** [comment]
Thanku for responsing  Sir. I used same config_infer_primary.txt in both of them . Could u say me please  which parameter must be change in yaml file tracker  until the 5 frame dose not lost

**Comment by marcoslucianops** [comment]
It's the `probationAge` parameter. Set it to 0.
